### PR TITLE
Fixes Some LinkedIn link issues and error handling

### PR DESCRIPTION
**Pull request by ArkaDutta-Maker**
- Fixes Some LinkedIn profile Links
- Added error handling for if profile was not present then linkedIn icon is removed

### CODE REVIEW

**Comment by Ayushpanditmoto** [comment]
@ArkaDutta-Maker 
I think its not required because we have already given all peope LinkedIn ids

**Comment by ArkaDutta-Maker** [comment]
@Ayushpanditmoto if you see sheetali maity linkedin link and shakya majumdar's linkedIn..you will find onw throws a 404 another one doesn't redirect. That's why I think it might be necessary

**Comment by Ayushpanditmoto** [comment]
But it will only hide LinkedIn icon whose linekdin id is null

**Comment by Ayushpanditmoto** [comment]
It will overall effect the website alignment

**Comment by ArkaDutta-Maker** [comment]
@Ayushpanditmoto ok..then what would be a better solution?

**Comment by Ayushpanditmoto** [comment]
There no better solution 😂 , can you work on dark mode is too much amoled black can you research on this

**Comment by ArkaDutta-Maker** [comment]
> There no better solution 😂 , can you work on dark mode is too much amoled black can you research on this 

Ok..on it

**Pull request closed without merging**
