### PR TITLE
Beautified Events Page Cards 

### PR DESCRIPTION
**Pull request by sau-mili**
Added the events cards side by side, Added onmouse effects on the images and fixed gaping between cards. #206

### CODE REVIEW

**Comment by Ayushpanditmoto** [comment]
@sau-mili  

 can you show me what changes you have made in video

**Comment by sau-mili** [comment]
https://github.com/GDSC-Jadavpur-University/GDSC-JU-Website/assets/146661411/d51a935e-dd75-4964-b497-a6e389e21d8a

This change..

**Comment by Ayushpanditmoto** [comment]
@sau-mili 😢😢 its too big 😂 i already fixed this page by myself for all devices
I think this fix not required you can see other gdsc website inspire from them then you can also raise some issues

**Comment by sau-mili** [comment]
Okay sure

**Pull request closed without merging**
