### PR TITLE
added new newsletter picture

### PR DESCRIPTION
**Pull request by FreemRL**
As wished from @Ayushpanditmoto I created this new PR because the new image wasn't included in the other PR

This is the new image that is included in here:
newsletter

But also included is the other picture here:
image

So you can choose which one you would like to display :)

### CODE REVIEW

**Comment by Ayushpanditmoto** [comment]
1st one

**Comment by FreemRL** [comment]
Yes feel free to use it they are both included in `/public` section 1st one is `newsletter.png` 2nd one is `Newsletter (1).png`

**Comment by sau-mili** [comment]
Screenshot 2023-10-05 025108
A text is appearing near the image. Check this

**Comment by Ayushpanditmoto** [comment]
@sau-mili do you want to fix this ??

**Comment by sau-mili** [comment]
@Ayushpanditmoto fixed this #193

**Pull request merged**
